# Generated by Django 5.2.7 on 2025-10-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="Наименование документа")),
                ("approved", models.BooleanField(default=False, verbose_name="Признак принятого документа")),
                ("path", models.CharField(max_length=255, verbose_name="Ссылка на документ")),
            ],
            options={
                "verbose_name": "Документ",
                "verbose_name_plural": "Документы",
            },
        ),
    ]
