# Generated by Django 5.2.7 on 2025-10-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docs_manager", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="path",
        ),
        migrations.AddField(
            model_name="document",
            name="file",
            field=models.FileField(default=None, upload_to="docs_manager/uploads"),
        ),
    ]
