# Generated by Django 5.2.7 on 2025-10-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docs_manager", "0003_remove_document_path_document_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(upload_to="docs_manager/uploads"),
        ),
    ]
