# Generated by Django 5.2.7 on 2025-10-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docs_manager", "0004_alter_document_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="approved",
        ),
        migrations.AddField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[("загружен", "загружен"), ("подтвержден", "подтвержден"), ("отклонен", "отклонен")],
                default="загружен",
                max_length=15,
                verbose_name="Статус документа",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="Дата и время обновления статуса"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name="Дата и время загрузки"),
        ),
    ]
