# Generated by Django 5.2.7 on 2025-10-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docs_manager", "0005_remove_document_approved_document_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[("Загружен", "Загружен"), ("Подтвержден", "Подтвержден"), ("Отклонен", "Отклонен")],
                default="Загружен",
                max_length=15,
                verbose_name="Статус документа",
            ),
        ),
    ]
