# Generated by Django 5.2.7 on 2025-10-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docs_manager", "0006_alter_document_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="updated_at",
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name="Дата и время обновления"),
        ),
    ]
