# Generated by Django 5.2.7 on 2025-10-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docs_manager", "0007_alter_document_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(upload_to="docs_manager/uploads", verbose_name="Файл"),
        ),
    ]
