[tool.poetry]
name = "diploma-work"
version = "0.1.0"
description = ""
authors = ["Anna <azeleranskaya@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
django = "^5.2.7"
djangorestframework = "^3.16.1"
djangorestframework-simplejwt = "^5.5.1"
dotenv = "^0.9.9"
psycopg2-binary = "^2.9.11"
celery = "^5.5.3"
redis = "^6.4.0"
drf-yasg = "^1.21.11"
django-cors-headers = "^4.9.0"


[tool.poetry.group.lint.dependencies]
flake8 = "^7.3.0"
black = "^25.9.0"
isort = "^7.0.0"


[tool.poetry.group.test.dependencies]
coverage = "^7.11.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 119
exclude = '.git'

[tool.isort]
line_length = 119
